// <auto-generated />
using System;
using Bank_System_PaySky.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank_System_PaySky.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20250503191150_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountModels.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AccountNumbers")
                        .HasColumnType("float");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountTransactionsModels.AccountTransactions", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCurrancy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.CurrencyModel.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsBase")
                        .HasColumnType("bit");

                    b.HasKey("CurrencyCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = "USD",
                            ExchangeRate = 1.0m,
                            IsBase = true
                        },
                        new
                        {
                            CurrencyCode = "EUR",
                            ExchangeRate = 0.96m,
                            IsBase = false
                        },
                        new
                        {
                            CurrencyCode = "GBP",
                            ExchangeRate = 0.80m,
                            IsBase = false
                        },
                        new
                        {
                            CurrencyCode = "EGP",
                            ExchangeRate = 50.86m,
                            IsBase = false
                        },
                        new
                        {
                            CurrencyCode = "SAR",
                            ExchangeRate = 3.76m,
                            IsBase = false
                        });
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.TransactionsModels.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.UserModels.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountModels.CheckingAccount", b =>
                {
                    b.HasBaseType("Bank_System_PaySky.Entities.AccountModels.Account");

                    b.Property<decimal>("Overdrafts")
                        .HasColumnType("decimal(18, 2)");

                    b.HasDiscriminator().HasValue("Checking");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountModels.SavingAccount", b =>
                {
                    b.HasBaseType("Bank_System_PaySky.Entities.AccountModels.Account");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18, 2)");

                    b.HasDiscriminator().HasValue("Savings");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountModels.Account", b =>
                {
                    b.HasOne("Bank_System_PaySky.Entities.CurrencyModel.Currency", "Currency")
                        .WithMany("Accounts")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bank_System_PaySky.Entities.UserModels.Users", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountTransactionsModels.AccountTransactions", b =>
                {
                    b.HasOne("Bank_System_PaySky.Entities.AccountModels.Account", "Account")
                        .WithMany("AccountTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bank_System_PaySky.Entities.TransactionsModels.Transaction", "Transaction")
                        .WithMany("AccountTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.AccountModels.Account", b =>
                {
                    b.Navigation("AccountTransactions");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.CurrencyModel.Currency", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.TransactionsModels.Transaction", b =>
                {
                    b.Navigation("AccountTransactions");
                });

            modelBuilder.Entity("Bank_System_PaySky.Entities.UserModels.Users", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
